apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - deployments.yaml
  - services.yaml
  - ingresses.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
commonLabels:
  app.kubernetes.io/name: pw2048
  app.kubernetes.io/managed-by: kustomize
